data# Generated by Django 5.2.7 on 2025-11-15 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('general', 'General Purpose'), ('web', 'Web Development'), ('data', 'Data Science'), ('mobile', 'Mobile'), ('system', 'System Programming'), ('other', 'Other')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'programming_languages',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('email_domain', models.CharField(blank=True, max_length=255)),
                ('normalized_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contributors',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('web_frontend', 'Web Frontend'), ('web_backend', 'Web Backend'), ('mobile', 'Mobile'), ('data_science', 'Data Science'), ('testing', 'Testing'), ('ui_library', 'UI Library'), ('build_tool', 'Build Tool'), ('database', 'Database/ORM'), ('other', 'Other')], default='other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frameworks', to='app.programminglanguage')),
            ],
            options={
                'db_table': 'frameworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('classification_type', models.CharField(choices=[('coding', 'Coding'), ('writing', 'Writing'), ('art', 'Art/Design'), ('mixed:coding+writing', 'Mixed: Coding + Writing'), ('mixed:coding+art', 'Mixed: Coding + Art'), ('mixed:writing+art', 'Mixed: Writing + Art'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('classification_confidence', models.FloatField(default=0.0)),
                ('project_root_path', models.CharField(blank=True, max_length=500)),
                ('project_tag', models.IntegerField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('code_files_count', models.IntegerField(default=0)),
                ('text_files_count', models.IntegerField(default=0)),
                ('image_files_count', models.IntegerField(default=0)),
                ('git_repository', models.BooleanField(default=False)),
                ('first_commit_date', models.DateTimeField(blank=True, null=True)),
                ('upload_source', models.CharField(default='zip_file', max_length=50)),
                ('original_zip_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_count', models.IntegerField(default=0)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_deleted', models.IntegerField(default=0)),
                ('percent_of_commits', models.FloatField(default=0.0)),
                ('net_lines', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='app.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='app.project')),
            ],
            options={
                'db_table': 'project_contributions',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('file_type', models.CharField(choices=[('code', 'Code'), ('content', 'Content/Text'), ('image', 'Image'), ('unknown', 'Unknown')], max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('line_count', models.IntegerField(blank=True, null=True)),
                ('character_count', models.IntegerField(blank=True, null=True)),
                ('content_preview', models.TextField(blank=True, max_length=10000)),
                ('is_content_truncated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.programminglanguage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.project')),
            ],
            options={
                'db_table': 'project_files',
            },
        ),
        migrations.CreateModel(
            name='ProjectFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_from', models.CharField(choices=[('dependencies', 'Dependency Files'), ('imports', 'Code Imports'), ('config', 'Configuration Files'), ('filenames', 'File Names')], default='dependencies', max_length=50)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.framework')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'db_table': 'project_frameworks',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(related_name='projects', through='app.ProjectFramework', to='app.framework'),
        ),
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_count', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programminglanguage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'db_table': 'project_languages',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='projects', through='app.ProjectLanguage', to='app.programminglanguage'),
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['email'], name='contributor_email_dda3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['normalized_name'], name='contributor_normali_d45554_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('name', 'email')},
        ),
        migrations.AddIndex(
            model_name='projectcontribution',
            index=models.Index(fields=['project', '-commit_count'], name='project_con_project_1af5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcontribution',
            index=models.Index(fields=['contributor', '-commit_count'], name='project_con_contrib_7994d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcontribution',
            unique_together={('project', 'contributor')},
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'file_type'], name='project_fil_project_2531b6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['file_extension'], name='project_fil_file_ex_dab864_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectframework',
            unique_together={('project', 'framework')},
        ),
        migrations.AlterUniqueTogether(
            name='projectlanguage',
            unique_together={('project', 'language')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='projects_user_id_58d805_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['classification_type'], name='projects_classif_c47eec_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['git_repository'], name='projects_git_rep_5c3662_idx'),
        ),
    ]
