# Generated by Django 5.2.7 on 2025-11-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_programminglanguage_user_bio_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
