# Generated by Django 5.2.8 on 2025-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_github_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='llm_consent',
            field=models.BooleanField(default=False),
        ),
    ]
