# Generated by Django 5.2.8 on 2025-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resume_bullet_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
