# Generated by Django 5.2.7 on 2026-01-12 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project_resume_bullet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('display_order', models.CharField(choices=[('manual', 'Manual Order'), ('contribution', 'By Contribution Score'), ('date', 'By Date'), ('name', 'Alphabetical')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('custom_description', models.TextField(blank=True)),
                ('custom_bullet_points', models.JSONField(blank=True, default=list)),
                ('use_custom_bullets', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('highlight', models.BooleanField(default=False)),
                ('include_in_resume', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='app.portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_memberships', to='app.project')),
            ],
            options={
                'db_table': 'portfolio_projects',
                'ordering': ['display_order', '-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='portfolios_user_id_f89dea_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['slug'], name='portfolios_slug_faed53_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['portfolio', 'display_order'], name='portfolio_p_portfol_7affec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioproject',
            unique_together={('portfolio', 'project')},
        ),
    ]
