# Generated by Django 5.2.7 on 2026-01-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_user_degree_major_user_education_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image_url",
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="project_thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
