# Generated by Django 6.0.1 on 2026-01-18 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_file_deduplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('target_audience', models.CharField(blank=True, max_length=100)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('technical', 'Technical'), ('creative', 'Creative')], default='professional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='app.portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='app.project')),
            ],
            options={
                'db_table': 'portfolio_projects',
                'ordering': ['order', '-added_at'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.ManyToManyField(related_name='portfolios', through='app.PortfolioProject', to='app.project'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['portfolio', 'order'], name='portfolio_p_portfol_dd7d8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioproject',
            unique_together={('portfolio', 'project')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', '-created_at'], name='portfolios_user_id_c744e0_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_public', '-created_at'], name='portfolios_is_publ_5fd03f_idx'),
        ),
    ]
