# Generated by Django 5.2.7 on 2026-01-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_portfolio_portfolioproject_portfolio_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
    ]
