# Generated by Django 6.0.1 on 2026-02-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_portfolio_portfolioproject_portfolio_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='code_files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_range_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_range_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='frameworks_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='languages_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stats_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='text_files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_commits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_contributors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_lines_of_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
    ]
