# Generated by Django 5.2.7 on 2026-02-22 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_portfolio_portfolioproject_portfolio_projects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("overall_score", models.FloatField(default=0.0)),
                ("category_scores", models.JSONField(default=dict)),
                ("rubric_evaluation", models.JSONField(default=dict)),
                ("code_quality_score", models.FloatField(default=0.0)),
                ("documentation_score", models.FloatField(default=0.0)),
                ("structure_score", models.FloatField(default=0.0)),
                ("testing_score", models.FloatField(default=0.0)),
                ("evidence", models.JSONField(default=dict)),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="app.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_evaluations",
                "indexes": [
                    models.Index(
                        fields=["language", "-overall_score"],
                        name="project_eva_languag_0ed0de_idx",
                    ),
                    models.Index(
                        fields=["project", "language"],
                        name="project_eva_project_f1b65a_idx",
                    ),
                ],
            },
        ),
    ]
