# Generated by Django 6.0.2 on 2026-02-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_portfolio_portfolioproject_portfolio_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_role',
            field=models.CharField(choices=[('solo_developer', 'Solo Developer'), ('lead_developer', 'Lead Developer'), ('contributor', 'Contributor'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('full_stack_developer', 'Full Stack Developer'), ('designer', 'Designer'), ('writer', 'Writer'), ('architect', 'Architect'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
