# Generated by Django 5.2.8 on 2026-03-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_add_user_role_to_project"),
        ("app", "0013_projectevaluation"),
    ]

    operations = []
