# Generated by Django 6.0.1 on 2026-01-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_project_frameworks_remove_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(related_name='projects', through='app.ProjectFramework', to='app.framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='projects', through='app.ProjectLanguage', to='app.programminglanguage'),
        ),
    ]
