# Generated by Django 6.0.1 on 2026-03-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_portfolio_stats_fields'),
        ('app', '0014_merge_20260301_1242'),
    ]

    operations = [
    ]
