# Generated by Django 5.2.7 on 2026-03-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_project_resume_skills'),
        ('app', '0015_merge_20260301_1818'),
    ]

    operations = [
    ]
