# Generated by Django 6.0.1 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_merge_20260308_2049"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="rendercv_yaml",
            field=models.TextField(blank=True, default="", help_text="Saved RenderCV YAML generated from the resume content"),
        ),
        migrations.AddField(
            model_name="resume",
            name="theme",
            field=models.CharField(blank=True, default="classic", help_text="RenderCV theme used when generating saved resume exports", max_length=64),
        ),
    ]