# Generated by Django 6.0.3 on 2026-03-30 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
def migrate_education_forward(apps, schema_editor):
    User = apps.get_model('app', 'User')
    Education = apps.get_model('app', 'Education')
    
    # Simple query: just iterate over all users
    for user in User.objects.all():
        # Only migrate if at least one field has content
        has_edu = bool(
            user.university or 
            user.degree_major or 
            user.education_city or 
            user.education_state or 
            user.expected_graduation
        )
        
        # We need to use `user.education_set` since the related name in models 
        # is probably the default depending on if `related_name="educations"` was defined.
        # Wait, the `Award` and `Education` models define `related_name="educations"`. Checked earlier.
        
        if has_edu and Education.objects.filter(user=user).count() == 0:
            edu_city = user.education_city or ''
            edu_state = user.education_state or ''
            location = f"{edu_city}, {edu_state}".strip(', ')
            
            expected_grad = user.expected_graduation

            Education.objects.create(
                user=user,
                institution=user.university or 'University',
                degree='',
                major=user.degree_major or '',
                location=location,
                end_date=expected_grad,
            )

def migrate_education_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_resume_rendercv_yaml_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'awards',
                'ordering': ['-date_received'],
                'indexes': [models.Index(fields=['user', '-date_received'], name='awards_user_id_f228df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education',
                'ordering': ['-end_date', '-start_date'],
                'indexes': [models.Index(fields=['user', '-end_date'], name='education_user_id_01fab2_idx')],
            },
        ),
        migrations.RunPython(migrate_education_forward, migrate_education_backward),
    ]
