# Generated by Django 6.0.3 on 2026-03-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_resume_rendercv_yaml_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_commit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
