# Generated by Django 6.0.3 on 2026-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_resume_rendercv_yaml_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skill_expertises",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
