# Generated by Django 6.0.3 on 2026-03-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_award_education'),
        ('app', '0018_user_skill_expertises'),
    ]

    operations = [
    ]
